export const TIERS = {
  starter: {
    name: "Starter",
    price: 3000,
    description: "Everything you need to build a consistent content presence",
    shortForm: 15,
    youtube: 0,
    shootDays: 1,
    smm: false,
    features: [
      "15 short-form videos per month",
      "1 shoot day per month",
      "Access to TFC's proprietary AI script-writing tool",
      "Content calendar & posting schedule",
    ],
  },
  core: {
    name: "Core",
    price: 5000,
    popular: true,
    description: "Full-service content production with social media management",
    shortForm: 30,
    youtube: 2,
    shootDays: 2,
    smm: true,
    features: [
      "30 short-form videos per month",
      "2 YouTube videos per month",
      "2 shoot days per month",
      "Access to TFC's proprietary AI script-writing tool",
      "Content calendar & posting schedule",
      "Social media management included",
    ],
  },
  premium: {
    name: "Premium",
    price: 7500,
    description: "The complete content machine for top-tier creators",
    shortForm: 45,
    youtube: 4,
    shootDays: 5,
    smm: true,
    features: [
      "45 short-form videos per month",
      "4 YouTube videos per month",
      "5 shoot days per month",
      "Access to TFC's proprietary AI script-writing tool",
      "Content calendar & posting schedule",
      "Social media management included",
      "Monthly strategy call",
      "Priority edit turnaround",
    ],
  },
} as const;

export type TierKey = keyof typeof TIERS;
